CHANGELOG.md
NewPlatform.Flexberry.ORM.ODataService.nuspec
NewPlatform.Flexberry.ORM.ODataService/Controllers/DataObjectController.ModifyData.cs
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/Create/BusinessServersTest.cs
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/GisCRUDTest.cs
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/Read/BuiltinQueryFunctionsTest.cs
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/Read/FilterByMasterFieldTest.cs
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/Read/FilterTest.cs
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/Read/MetaDataTest.cs
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/Read/ReferenceToMasterTest.cs
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/Read/SkipTopOrderByTest.cs
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/Read/UtfRequestsTest.cs
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/Update/ModifyDataTest.cs
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/Events/AfterSaveTest.cs
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/Events/BeforeSaveTest.cs
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/Extensions/DataObjectExtensions.cs
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/Files/FileDescriptionTest.cs
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/Functions/ActionsTest.cs
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/Functions/DelegateFunctionsTest.cs
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/Functions/FunctionsTest.cs
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/Helpers/DataObjectDictionary.cs
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/Helpers/DataObjectDictionaryCollection.cs
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/Model/CustomizationEdmModelNames.cs

https://www.newtonsoft.com/json/help/html/JsonNetVsDotNetSerializers.htm#Benchmarks

JavaScriptSerializer replaced with JsonConvert for better performance.

---

NewPlatform.Flexberry.ORM.ODataService/Controllers/DataObjectController.cs
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/Read/BuiltinQueryFunctionsTest.cs

Теперь для получения используется динамическое представление + добавлен тест для проверки запросов

Исправлено получение объекта из сервиса данных 

---

NewPlatform.Flexberry.ORM.ODataService.nuspec
NewPlatform.Flexberry.ORM.ODataService/Batch/DataObjectODataBatchHandler.cs
NewPlatform.Flexberry.ORM.ODataService/Controllers/DataObjectController.ModifyData.cs
NewPlatform.Flexberry.ORM.ODataService/Extensions/HttpConfigurationExtensions.cs
NewPlatform.Flexberry.ORM.ODataService/Handlers/PostPatchHandler.cs
NewPlatform.Flexberry.ORM.ODataService/NewPlatform.Flexberry.ORM.ODataService.csproj
NewPlatform.Flexberry.ORM.ODataService/Routing/DataObjectRoutingConvention.cs
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/BaseODataServiceIntegratedTest.cs
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/SelfHostBaseODataServiceIntegratedTest.cs

Implementation $batch requests support #30.

Add batch requests support

---

NewPlatform.Flexberry.ORM.ODataService.nuspec
NewPlatform.Flexberry.ORM.ODataService/Model/DynamicView.cs

Alternative solution for Flexberry/NewPlatform.Flexberry.ORM#55.

Add the primary key of the master in the dynamic view

---

NewPlatform.Flexberry.ORM.ODataService.nuspec
NewPlatform.Flexberry.ORM.ODataService/Batch/DataObjectODataBatchHandler.cs
NewPlatform.Flexberry.ORM.ODataService/Controllers/DataObjectController.ModifyData.cs
NewPlatform.Flexberry.ORM.ODataService/Controllers/DataObjectController.cs
NewPlatform.Flexberry.ORM.ODataService/DataObjectControllerActivator.cs
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/Create/BusinessServersTest.cs
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/Update/ModifyDataTest.cs
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/Events/AfterSaveTest.cs
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/Events/BeforeSaveTest.cs
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/Model/CustomizationEdmModelNames.cs

Add common DataObjectCache for all sql queries per http request

---

Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/GisCRUDTest.cs
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/Read/BuiltinQueryFunctionsTest.cs
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/Read/FilterByMasterFieldTest.cs
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/Read/FilterTest.cs
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/Read/SkipTopOrderByTest.cs
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/Events/BeforeGetTest.cs

Для получение имени модели используется args.Token.Model.GetEdmEntitySet.

Fixed requestUrl for some tests.

---

NewPlatform.Flexberry.ORM.ODataService.nuspec
NewPlatform.Flexberry.ORM.ODataService/Controllers/DataObjectController.cs

Fix Flexberry/ember-flexberry#943
Also need update NewPlatform.Flexberry.Reports.ExportToExcel package to v1.0.0-alpha09 or higher.

Fix naming of details when exporting data to Excel

---

NewPlatform.Flexberry.ORM.ODataService.nuspec
NewPlatform.Flexberry.ORM.ODataService/Model/DynamicView.cs
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/Read/FilterByMasterDetailFieldTest.cs

Fix complex master detail predicate

---

CHANGELOG.md
NewPlatform.Flexberry.ORM.ODataService.nuspec
NewPlatform.Flexberry.ORM.ODataService/DataObjectControllerActivator.cs

Add virtual methods in controller activator

---

NewPlatform.Flexberry.ORM.ODataService.nuspec
NewPlatform.Flexberry.ORM.ODataService/Controllers/DataObjectController.ModifyData.cs
NewPlatform.Flexberry.ORM.ODataService/Controllers/DataObjectController.cs
NewPlatform.Flexberry.ORM.ODataService/Handlers/ExtendedODataPathHandler.cs
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/Create/CreateWithPseudoDetailDefinedTest.cs
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/Read/FilterByPseudoDetailFieldTest.cs
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/NewPlatform.Flexberry.ORM.ODataService.Tests.csproj

Fix creation of DataObject instance with pseudodetail field defined.

---

Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/BaseIntegratedTest.cs
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/BaseODataServiceIntegratedTest.cs
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/GisCRUDTest.cs
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/Read/BuiltinQueryFunctionsTest.cs

#96 Skip Gis CRUD tests on Oracle.

Skip Gis CRUD tests on Oracle. Base date in TestFilterNow() method of

---

Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/NewPlatform.Flexberry.ORM.ODataService.Tests.csproj
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/packages.config

it fixes mssql integration tests on agent without MSSQL on board

Add Microsoft.SqlServer.Types for tests

---

Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/BaseIntegratedTest.cs

Use single access for conn string in config

---

CHANGELOG.md
NewPlatform.Flexberry.ORM.ODataService.Files/FileDescription.cs
NewPlatform.Flexberry.ORM.ODataService.Files/Providers/BaseDataObjectFileProvider.cs
NewPlatform.Flexberry.ORM.ODataService.WebApi/Controllers/FileController.cs
NewPlatform.Flexberry.ORM.ODataService.nuspec
NewPlatform.Flexberry.ORM.ODataService/Controllers/DataObjectController.ModifyData.cs
NewPlatform.Flexberry.ORM.ODataService/Model/DataObjectEdmModel.cs
NewPlatform.Flexberry.ORM.ODataService/Model/DefaultDataObjectEdmModelBuilder.cs
NewPlatform.Flexberry.ORM.ODataService/Model/EdmTypeMap.cs
NewPlatform.Flexberry.ORM.ODataService/Model/IDataObjectEdmModelBuilder.cs

* Add file property type in file description. Remove files through file provider.
* Add additional edm mapping into model builder.

Own file provider (#135)

---

.github/workflows/main.yml
Doxygen/update-autodoc.sh
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/App.config

Add GitHub Actions for develop-v5.2

---

CHANGELOG.md
NewPlatform.Flexberry.ORM.ODataService.nuspec
NewPlatform.Flexberry.ORM.ODataService/Controllers/DataObjectController.cs
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/Events/BeforeGetTest.cs

Add test for Count and BeforeGet

---

CHANGELOG.md
NewPlatform.Flexberry.ORM.ODataService.nuspec
NewPlatform.Flexberry.ORM.ODataService/Model/DynamicView.cs
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/Read/FilterByMasterDetailFieldTest.cs

Add test filter by enum detail master

---

NewPlatform.Flexberry.ORM.ODataService.nuspec
NewPlatform.Flexberry.ORM.ODataService/Controllers/DataObjectController.Actions.cs
NewPlatform.Flexberry.ORM.ODataService/Controllers/DataObjectController.UserFunctions.cs
NewPlatform.Flexberry.ORM.ODataService/Functions/Action.cs
NewPlatform.Flexberry.ORM.ODataService/Functions/Delegates.cs
NewPlatform.Flexberry.ORM.ODataService/Functions/Function.cs
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/Functions/ActionsTest.cs

Realization of https://github.com/Flexberry/NewPlatform.Flexberry.ORM.ODataService/issues/180.
Fixes #180.

Add action with void response

---

CHANGELOG.md
NewPlatform.Flexberry.ORM.ODataService.nuspec
NewPlatform.Flexberry.ORM.ODataService/Controllers/DataObjectController.UserFunctions.cs
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/Functions/FunctionsTest.cs

Fix user function Edm.Binary (byte[]) response.

Fix user function Edm.Binary response.

---

.github/workflows/build.yml
CHANGELOG.md
NewPlatform.Flexberry.ORM.ODataService.Files/NewPlatform.Flexberry.ORM.ODataService.Files.csproj
NewPlatform.Flexberry.ORM.ODataService.WebApi/NewPlatform.Flexberry.ORM.ODataService.WebApi.csproj
NewPlatform.Flexberry.ORM.ODataService.nuspec
NewPlatform.Flexberry.ORM.ODataService/NewPlatform.Flexberry.ORM.ODataService.csproj
NewPlatform.Flexberry.ORM.ODataServiceCore.Common/NewPlatform.Flexberry.ORM.ODataServiceCore.Common.csproj
Samples/ODataServiceSample.AspNet/ODataServiceSample.AspNet.csproj
Samples/ODataServiceSample.AspNet/Web.config
Samples/ODataServiceSample.AspNet/packages.config
Samples/ODataServiceSample.AspNetCore/ODataServiceSample.AspNetCore.csproj
Tests/BusinessServers/NewPlatform.Flexberry.ORM.ODataService.Tests.BusinessServers.csproj
Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/NewPlatform.Flexberry.ORM.ODataService.Tests.csproj
Tests/Objects/NewPlatform.Flexberry.ORM.ODataService.Tests.Objects.csproj

Update NewPlatform.Flexberry.ORM.ODataService up to 6.2.0.
Update depending NewPlatform.Flexberry.ORM up to 6.1.0

Feature update to 6.2.0

---

.github/workflows/sonar.yml

В билдах сонара проблема, что версия Java не подходит.
Перевод с 11 на 17 версию.

Try to fix sonar build
